# Generated by Django 5.2.6 on 2026-04-18 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='users',
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.PROTECT, related_name='lessons_as_tutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TutorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='предмет')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активна'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='статус связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата привязки')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tutors', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'связь репетитор-ученик',
                'verbose_name_plural': 'связи репетитор-ученик',
                'constraints': [models.UniqueConstraint(fields=('tutor', 'student'), name='unique_tutor_student_pair')],
            },
        ),
    ]
