# Generated by Django 5.2.6 on 2026-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lesson_users_lesson_students_lesson_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorstudent',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активна'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='статус связи'),
        ),
    ]
