# Generated by Django 5.2.6 on 2026-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tutorstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_recurring_weekly',
            field=models.BooleanField(default=False, verbose_name='еженедельное повторение'),
        ),
    ]
