# Generated by Django 5.2.6 on 2026-04-30 13:51

import assignments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Предмет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Репетитор')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignments.models.assignment_file_path, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('submitted', 'Сдано'), ('graded', 'Проверено')], default='assigned', max_length=20, verbose_name='Статус')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('tutor_comment', models.TextField(blank=True, verbose_name='Комментарий репетитора')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время сдачи')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='assignments.assignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначение ученику',
                'verbose_name_plural': 'Назначения ученикам',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignments.models.submission_file_path, verbose_name='Файл ответа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='assignments.studentassignment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentassignment',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'),
        ),
    ]
