# Generated by Django 5.2.6 on 2026-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_grade',
            field=models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Максимальная оценка'),
        ),
    ]
