# Generated by Django 6.0.5 on 2026-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_max_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='student_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий ученика'),
        ),
    ]
